# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'VisaMovie' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VisaMovie
  pod 'SwiftyJSON'
  pod 'AFNetworking'

end
